# --- Experiment configurations --------------------------------------------------------------------

# experiment name, used as folder name
experiment_name: 6_basin_dev

# files to specify training, validation and test basins (relative to code root or absolute path)
train_basin_file: basin_lists/dev/6_dev_basins.txt
validation_basin_file: basin_lists/dev/6_dev_basins.txt
test_basin_file: basin_lists/dev/6_dev_basins.txt

# training, validation and test time periods (format = 'dd/mm/yyyy')
train_start_date: '01/10/2000'
train_end_date: '30/09/2002'
validation_start_date: '01/10/2003'
validation_end_date: '30/09/2005'
test_start_date: '01/10/2006'
test_end_date: '30/09/2008'

# which GPU (id) to use [in format of cuda:0, cuda:1 etc, or cpu or None]
device: cuda:0

# --- Validation configuration ---------------------------------------------------------------------

# specify after how many epochs to perform validation
validate_every: 3

# specify how many random basins to use for validation
validate_n_random_basins: 1

# specify which metrics to calculate during validation (see neuralhydrology.evaluation.metrics)
# this can either be a list or a dictionary. If a dictionary is used, the inner keys must match the name of the
# target_variable specified below. Using dicts allows for different metrics per target variable.
metrics:
- NSE

# --- Model configuration --------------------------------------------------------------------------

# base model type [lstm, ealstm, cudalstm, embcudalstm, mtslstm]
# (has to match the if statement in modelzoo/__init__.py)
model: cudalstm

# prediction head [regression]. Define the head specific parameters below
head: regression

# ----> Regression settings <----
output_activation: linear

# ----> General settings <----

# Number of cell states of the LSTM
hidden_size: 20

# Initial bias value of the forget gate
initial_forget_bias: 3

# Dropout applied to the output of the LSTM
output_dropout: 0.4

# --- Training configuration -----------------------------------------------------------------------

# specify optimizer [Adam]
optimizer: Adam

# specify loss [MSE, NSE, RMSE]
loss: MSE

# specify learning rates to use starting at specific epochs (0 is the initial learning rate)
learning_rate:
    0: 1e-2
    30: 5e-3
    40: 1e-3

# Mini-batch size
batch_size: 256

# Number of training epochs
epochs: 50

# If a value, clips the gradients during training to that norm.
clip_gradient_norm: 1

# Defines which time steps are used to calculate the loss. Can't be larger than seq_length.
# If use_frequencies is used, this needs to be a dict mapping each frequency to a predict_last_n-value, else an int.
predict_last_n: 1

# Length of the input sequence
# If use_frequencies is used, this needs to be a dict mapping each frequency to a seq_length, else an int.
seq_length: 365

# Number of parallel workers used in the data pipeline
num_workers: 8

# Log the training loss every n steps
log_interval: 5

# If true, writes logging results into tensorboard file
log_tensorboard: True

# If a value and greater than 0, logs n random basins as figures during validation
log_n_figures: 1

# Save model weights every n epochs
save_weights_every: 1

# --- Data configurations --------------------------------------------------------------------------

# which data set to use [camels_us, camels_gb, global, hourly_camels_us]
dataset: caravan

# Path to data set root
data_dir: /home/gsnearing_google_com/caravan-data/Caravan

# Forcing product [daymet, maurer, maurer_extended, nldas, nldas_extended, nldas_hourly]
# can be either a list of forcings or a single forcing product
forcings:
- caravan

dynamic_inputs:
 - snow_depth_water_equivalent_mean
 - surface_net_solar_radiation_mean
 - surface_net_thermal_radiation_mean
 - surface_pressure_mean
 - temperature_2m_mean
 - dewpoint_temperature_2m_mean
 - u_component_of_wind_10m_mean
 - v_component_of_wind_10m_mean
 - volumetric_soil_water_layer_1_mean
 - volumetric_soil_water_layer_2_mean
 - volumetric_soil_water_layer_3_mean
 - volumetric_soil_water_layer_4_mean
 - snow_depth_water_equivalent_min
   # - surface_net_solar_radiation_min
 - surface_net_thermal_radiation_min
 - surface_pressure_min
 - temperature_2m_min
 - dewpoint_temperature_2m_min
 - u_component_of_wind_10m_min
 - v_component_of_wind_10m_min
 - volumetric_soil_water_layer_1_min
 - volumetric_soil_water_layer_2_min
 - volumetric_soil_water_layer_3_min
 - volumetric_soil_water_layer_4_min
 - snow_depth_water_equivalent_max
 - surface_net_solar_radiation_max
 - surface_net_thermal_radiation_max
 - surface_pressure_max
 - temperature_2m_max
 - dewpoint_temperature_2m_max
 - u_component_of_wind_10m_max
 - v_component_of_wind_10m_max
 - volumetric_soil_water_layer_1_max
 - volumetric_soil_water_layer_2_max
 - volumetric_soil_water_layer_3_max
 - volumetric_soil_water_layer_4_max
 - total_precipitation_sum
 - potential_evaporation_sum

# which columns to use as target
target_variables:
 - streamflow

# clip negative predictions to zero for all variables listed below. Should be a list, even for single variables.
clip_targets_to_zero:
 - streamflow
